#!/bin/zsh
# Force delete the old container and re-initialize the container.
sudo docker rm -f security-layer

# Build the Docker image.
sudo docker build --tag security-layer:latest .

# Create a Docker container from the image and connect host port 8000 to container port 8000.
sudo docker run --name security-layer -d -p 8000:8000 security-layer:latest
