#!/bin/zsh
# Force delete the old container and re-initialize the container.
docker rm -f security-layer

# Build the Docker image.
docker build --tag security-layer:latest .

# Create a Docker container from the image and connect host port 8000 to container port 8000.
docker run --name security-layer -d -p 8000:8000 security-layer:latest
